version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres1
    ports:
      - '${DATABASE_PORT}:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: